SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1267914693491912705'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(396,398)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(451,450)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(300,301,302)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479236333516165121'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479007307744755712'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150776249290752'
COMMIT;
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(452)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
