UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478611830633283586'
SELECT g_status_id FROM status_groups WHERE owner_id='1479345335860621312' AND preview_draft_id='1'
BEGIN EXCLUSIVE;
SELECT _id, timeline_owner_id, timeline_type, timeline_entity_id, timeline_flags, timeline_entity_group_id  FROM timeline_view WHERE timeline_data_type=1 AND timeline_data_id='2954391680'
DELETE FROM timeline WHERE _id='895'
DELETE FROM timeline WHERE _id='896'
DELETE FROM timeline WHERE _id='897'
DELETE FROM timeline WHERE _id='898'
SELECT _id, status_id, in_r_status_id, in_r_user_id, flags  FROM statuses WHERE status_id='2954391680'
UPDATE statuses SET flags=256,in_r_user_id='-1',in_r_status_id='-1' WHERE _id='390'
UPDATE statuses SET in_r_user_id='0',in_r_status_id='0' WHERE in_r_status_id='2954391680'
DELETE FROM status_groups WHERE g_status_id='2954391680'
COMMIT;
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10026364234')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479163490501812225'
SELECT COUNT(*) FROM conversations WHERE last_readable_event_id > last_read_event_id AND trusted=1 AND last_readable_event_id > (SELECT COALESCE((SELECT CAST(next as int) AS last_seen_event_id FROM cursors WHERE kind=17 AND type=0 ORDER BY last_seen_event_id DESC LIMIT 1), 0));
SELECT _id, kind, type, owner_id, ref_id, next  FROM cursors WHERE (type=0) AND (kind=18) ORDER BY ref_id DESC
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='12' AND ref_id IS NULL
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='12' AND ref_id IS NULL
SELECT COUNT(_id)  FROM conversation_entries
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='19' AND ref_id IS NULL
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='20' AND ref_id IS NULL
BEGIN EXCLUSIVE;
COMMIT;
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (data_source='urt_pin_entries')
BEGIN EXCLUSIVE;
SELECT entity_id, preview_id  FROM timeline WHERE owner_id='1479345335860621312' AND type='7' AND is_preview=1
SELECT entity_id, data_type_tag  FROM timeline WHERE owner_id='1479345335860621312' AND type='7'
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_id IN('cursor-bottom-1641539152583','cursor-top-1641539152585'))
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_group_id IN())
SELECT MAX(updated_at)  FROM timeline WHERE owner_id='1479345335860621312' AND type='7'
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-top-1641539152585',x'','cursor-top-1641539152585',1641539152585,14,2,'',NULL,x'',NULL,NULL,x'496a4f444141424441414243674142464965777672776163414149414149414141414243414144535133624551674142444e51567563414377414341414141433046594e4870584e6e4a4a5a3370334141411202381c7058beda58',7,1641539152585,9223372036854775807,0,13,1641539842594,1884864218,NULL,1479345335860621312,NULL,NULL,0)
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-bottom-1641539152583',x'','cursor-bottom-1641539152583',1641539152583,14,2,'',NULL,x'',NULL,NULL,x'496a4f444141434441414243674142464965777672776163414149414149414141414243414144535133624551674142444e51567563414377414341414141433046594e4870584e6e4a4a5a3370334141411203381dffffffff895a109858',7,1641539152585,9223372036854775807,0,13,1641539842594,-1990586216,NULL,1479345335860621312,NULL,NULL,0)
SELECT timeline_chunk_id, COUNT(*)  FROM timeline WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL) GROUP BY timeline_chunk_id ORDER BY timeline_chunk_id
COMMIT;
UPDATE timeline SET should_highlight=0 WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)
UPDATE timeline SET should_highlight=1 WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (sort_index>1641539152584)
SELECT COUNT(*) FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (should_highlight='1') AND (data_type=27)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479037539159887874'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478995016391532546'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479014532978778115'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478765671047741444'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(1167,1166,1171,1170)
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479259075355447296'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479215197617336326'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479068549196828672'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479027589591166980'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150776249290752'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479154551991189513'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223201850867714'
COMMIT;
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479259075355447296'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479068549196828672'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479027589591166980'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150776249290752'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223201850867714'
COMMIT;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479102839146176518'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1432444494712958976')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1432444494712958976')
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1477370959757811712'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150502470373383'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(1751,1750,1749)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1477693684007280641'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1475545780584861696'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
COMMIT;
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('848920371311001600')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1362135345043673092')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479131311965032457'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479143390092660742'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10045544167')
SELECT _id, user_id, username, name, image_url, user_flags, user_label_data, is_profile_translatable, friendship, friendship_time, are_dms_muted, is_active_creator, profile_image_colors, has_nft_avatar, header_url, description, link_color, web_url, url_entities, bg_color, extended_profile_fields, location, structured_location, followers, fast_followers, friends, statuses, favorites, media_count, profile_created, updated, pinned_tweet_id, advertiser_type, hash, translator_type, profile_interstitial_type, profile_banner_colors, withheld_info, tip_jar_settings, smart_blocking_expiration, professional  FROM users WHERE user_id='20408471'
SELECT _id, user_id, username, name, image_url, user_flags, user_label_data, is_profile_translatable, friendship, friendship_time, are_dms_muted, is_active_creator, profile_image_colors, has_nft_avatar, header_url, description, link_color, web_url, url_entities, bg_color, extended_profile_fields, location, structured_location, followers, fast_followers, friends, statuses, favorites, media_count, profile_created, updated, pinned_tweet_id, advertiser_type, hash, translator_type, profile_interstitial_type, profile_banner_colors, withheld_info, tip_jar_settings, smart_blocking_expiration, professional  FROM users WHERE user_id='1318236788541038594'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(2196,2096,2095,2094,2093)
SELECT name, query, type, query_id, user_search_suggestion, topic_search_suggestion, time, score FROM search_queries WHERE (name LIKE '%' AND query!='' AND query NOT LIKE 'place:%') AND (type IN (0,2,12)) ORDER BY score DESC, time DESC
SELECT name, query, type, query_id, user_search_suggestion, topic_search_suggestion, min(priority) FROM search_queries WHERE (name LIKE '%' AND query!='' AND query NOT LIKE 'place:%') AND (type IN (11)) GROUP BY name ORDER BY type ASC, query_id DESC, time DESC
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10026653538')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1432444494712958976')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479052622279725060'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1352681651516567553')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479229074388275203'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479002026084343812'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10027232467')
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479126025447616515'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10027232467')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1352681651516567553')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479106485791510529'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10027232467')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479289335841103878'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479161573457350659'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479181802917052416'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150061208711173'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1129035372757827584')
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076058284662789'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479054039027490817'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479002026084343812'
UPDATE statuses SET favorite_count=5027 WHERE status_id='1479002026084343812'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479102839146176518'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478991246232371201'
UPDATE statuses SET favorite_count=183 WHERE status_id='1478991246232371201'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479229074388275203'
UPDATE statuses SET favorite_count=13234 WHERE status_id='1479229074388275203'
COMMIT;
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076058284662789'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479054039027490817'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479002026084343812'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479102839146176518'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478991246232371201'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479229074388275203'
COMMIT;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1220297921100468224'
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076058284662789'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479054039027490817'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479002026084343812'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479102839146176518'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478991246232371201'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479229074388275203'
COMMIT;
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076058284662789'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479054039027490817'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479002026084343812'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479102839146176518'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478991246232371201'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479229074388275203'
COMMIT;
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076058284662789'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479054039027490817'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479002026084343812'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479102839146176518'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478991246232371201'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479229074388275203'
COMMIT;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479019699589550081'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479106536844652554'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478894576643547140'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479154513525317640'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478991246232371201'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479210217451700225'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076717729775617'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(3082,3081,3092,3091,3090,3089,3088,3087,3086,3085,3084,3083)
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479169397579255808'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478263934536675328'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478146943264120835'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='477377257703759873'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='116767752026460161'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='80619168881315841'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
