SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1398203555236962304'
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='12' AND ref_id IS NULL
SELECT COUNT(_id)  FROM conversation_entries
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='19' AND ref_id IS NULL
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='20' AND ref_id IS NULL
BEGIN EXCLUSIVE;
COMMIT;
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (data_source='urt_pin_entries')
BEGIN EXCLUSIVE;
SELECT entity_id, preview_id  FROM timeline WHERE owner_id='1479345335860621312' AND type='7' AND is_preview=1
SELECT entity_id, data_type_tag  FROM timeline WHERE owner_id='1479345335860621312' AND type='7'
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_id IN('cursor-bottom-1641539152583','cursor-top-1641539152585'))
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_group_id IN())
SELECT MAX(updated_at)  FROM timeline WHERE owner_id='1479345335860621312' AND type='7'
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-top-1641539152585',x'','cursor-top-1641539152585',1641539152585,14,2,'',NULL,x'',NULL,NULL,x'496a4f444141424441414243674142464965777672776163414149414149414141414243414144535133624551674142444e51567563414377414341414141433046594e4870584e6e4a4a5a3370334141411202381c7058beda58',7,1641539152585,9223372036854775807,0,13,1641539766437,1884864218,NULL,1479345335860621312,NULL,NULL,0)
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-bottom-1641539152583',x'','cursor-bottom-1641539152583',1641539152583,14,2,'',NULL,x'',NULL,NULL,x'496a4f444141434441414243674142464965777672776163414149414149414141414243414144535133624551674142444e51567563414377414341414141433046594e4870584e6e4a4a5a3370334141411203381dffffffff895a109858',7,1641539152585,9223372036854775807,0,13,1641539766437,-1990586216,NULL,1479345335860621312,NULL,NULL,0)
SELECT timeline_chunk_id, COUNT(*)  FROM timeline WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL) GROUP BY timeline_chunk_id ORDER BY timeline_chunk_id
COMMIT;
UPDATE timeline SET should_highlight=0 WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)
UPDATE timeline SET should_highlight=1 WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (sort_index>1641539152584)
SELECT COUNT(*) FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (should_highlight='1') AND (data_type=27)
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479351162302529536'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479027589591166980'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479146729014505479'
UPDATE timeline SET is_read=1 WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='12' AND ref_id IS NULL
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
BEGIN EXCLUSIVE;
UPDATE conversations SET draft_message=NULL WHERE conversation_id='1479345335860621312-1479345335860621312'
COMMIT;
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='12' AND ref_id IS NULL
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT _id, conversations_conversation_id, conversations_title, conversations_avatar, conversations_type, conversations_sort_event_id, conversations_last_readable_event_id, conversations_last_read_event_id, conversations_sort_timestamp, conversations_is_conversation_muted, conversations_min_event_id, conversations_is_hidden, conversations_has_more, conversations_read_only, conversations_trusted, conversations_draft_message, conversations_local_conversation_id, conversations_mute_expiration_time, conversations_is_mentions_muted, conversations_draft_media_id, conversations_low_quality, conversations_is_muted, conversations_contains_nsfw_content, conversations_score, conversations_social_proof, conversations_label, is_unread  FROM dm_inbox WHERE (conversations_sort_event_id!=0) AND (conversations_trusted=1) ORDER BY conversations_sort_event_id DESC
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT _id, conversation_entries_entry_id, conversation_entries_sort_entry_id, conversation_entries_conversation_id, conversation_entries_user_id, conversation_entries_created, conversation_entries_entry_type, conversation_entries_data, conversation_entries_request_id, conversation_entries_linked_entry_id, users_username, users_name, users_image_url, users_has_nft_avatar, is_unread, is_first_entry, max_sort_entry_id  FROM most_recent_conversation_item
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479277371362533378'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(1115,1114,1121,1120)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(1234,1211,1233,1199,1210,1232,1198,1231,1197,1230,1196,1195,1194,1193,1206,1228,1205,1227,1226,1203,1225,1202,1224,1201,1223,1200,1209,1208,1207,1229)
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(899)
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='12' AND ref_id IS NULL
SELECT COUNT(_id)  FROM conversation_entries
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='19' AND ref_id IS NULL
SELECT next  FROM cursors WHERE owner_id='1479345335860621312' AND type='0' AND kind='20' AND ref_id IS NULL
BEGIN EXCLUSIVE;
COMMIT;
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (data_source='urt_pin_entries')
BEGIN EXCLUSIVE;
SELECT entity_id, preview_id  FROM timeline WHERE owner_id='1479345335860621312' AND type='7' AND is_preview=1
SELECT entity_id, data_type_tag  FROM timeline WHERE owner_id='1479345335860621312' AND type='7'
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_id IN('cursor-bottom-1641539152583','cursor-top-1641539152585'))
DELETE FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_group_id IN())
SELECT MAX(updated_at)  FROM timeline WHERE owner_id='1479345335860621312' AND type='7'
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-top-1641539152585',x'','cursor-top-1641539152585',1641539152585,14,2,'',NULL,x'',NULL,NULL,x'496a4f444141424441414243674142464965777672776163414149414149414141414243414144535133624551674142444e51567563414377414341414141433046594e4870584e6e4a4a5a3370334141411202381c7058beda58',7,1641539152585,9223372036854775807,0,13,1641539928353,1884864218,NULL,1479345335860621312,NULL,NULL,0)
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-bottom-1641539152583',x'','cursor-bottom-1641539152583',1641539152583,14,2,'',NULL,x'',NULL,NULL,x'496a4f444141434441414243674142464965777672776163414149414149414141414243414144535133624551674142444e51567563414377414341414141433046594e4870584e6e4a4a5a3370334141411203381dffffffff895a109858',7,1641539152585,9223372036854775807,0,13,1641539928354,-1990586216,NULL,1479345335860621312,NULL,NULL,0)
SELECT timeline_chunk_id, COUNT(*)  FROM timeline WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL) GROUP BY timeline_chunk_id ORDER BY timeline_chunk_id
COMMIT;
UPDATE timeline SET should_highlight=0 WHERE (type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)
UPDATE timeline SET should_highlight=1 WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (sort_index>1641539152584)
SELECT COUNT(*) FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (should_highlight='1') AND (data_type=27)
DELETE FROM timeline WHERE ((type=8) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (data_source='urt_pin_entries')
BEGIN EXCLUSIVE;
SELECT entity_id, preview_id  FROM timeline WHERE owner_id='1479345335860621312' AND type='8' AND is_preview=1
SELECT entity_id, data_type_tag  FROM timeline WHERE owner_id='1479345335860621312' AND type='8'
DELETE FROM timeline WHERE ((type=8) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_id IN('cursor-top-1'))
DELETE FROM timeline WHERE ((type=8) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (entity_group_id IN())
SELECT MAX(updated_at)  FROM timeline WHERE owner_id='1479345335860621312' AND type='8'
INSERT INTO timeline(data_type_group,is_dispensable,data_source,prompt,entity_group_id,social_context,entity_id,sort_index,data_type,updated_at,dismiss_feedback_key,data_type_tag,scribe_content,preview_id,pc,data,type,timeline_chunk_id,expiry_time,is_preview,entity_type,created_at,data_id,timeline_tag,owner_id,entity_flattening_id,display_context,is_read) VALUES (NULL,0,'urt_add_entries',x'','cursor-top-1',x'','cursor-top-1',1,14,1,'',NULL,x'',NULL,NULL,x'496a4f444141424441414243674142464965777672776163414149414149414141414343414144535133624551674142444e576d6877414377414341414141433046425155464251554642515546424141411202381dffffffff83bfb44058',8,1,9223372036854775807,0,13,1641539928613,-2084588480,NULL,1479345335860621312,NULL,NULL,0)
SELECT timeline_chunk_id, COUNT(*)  FROM timeline WHERE (type=8) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL) GROUP BY timeline_chunk_id ORDER BY timeline_chunk_id
COMMIT;
UPDATE timeline SET should_highlight=0 WHERE (type=8) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)
UPDATE timeline SET should_highlight=1 WHERE ((type=8) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (sort_index>1641539152584)
SELECT COUNT(*) FROM timeline WHERE ((type=7) AND (owner_id=1479345335860621312) AND (timeline_tag IS NULL)) AND (should_highlight='1') AND (data_type=27)
SELECT impression_id, event, is_earned, trend_id, num_retries, url, video_content_uuid, video_content_type, legacy_card_event, engagement_metadata, timestamp, unified_card_event  FROM promoted_retry
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1194365176272699392')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('847896837532995585')
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479068549196828672'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150776249290752'
COMMIT;
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479068549196828672'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150776249290752'
COMMIT;
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(1533,1532,1531,1530,1529,1528)
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479068549196828672'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479150776249290752'
COMMIT;
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(1866,1875,1874,1862,1873,1861,1872,1860,1871,1870,1859,1858,1869,1857,1868,1856,1878)
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1477655934835081216'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1475542006520811528'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1194365176272699392')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1432444494712958976')
BEGIN EXCLUSIVE;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479223945597526020'
COMMIT;
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1362135345043673092')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1362135345043673092')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479076058284662789'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479143282248671234'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10026653538')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478732517997961218'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479230483854548993'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id  FROM search_queries WHERE LOWER(query)=LOWER('databricks') AND LOWER(name)=LOWER('Databricks') AND type='2' AND latitude IS NULL AND longitude IS NULL
BEGIN EXCLUSIVE;
INSERT INTO search_queries(latitude,topic_search_suggestion,query_id,priority,radius,user_search_suggestion,name,time,type,query,longitude,location) VALUES (NULL,NULL,1562518867,3,NULL,x'4a031c5d2225536a0a64617461627269636b736a0a44617461627269636b736a4c68747470733a2f2f7062732e7477696d672e636f6d2f70726f66696c655f696d616765732f313431303636353933353635373037343639312f306645474b7639325f6e6f726d616c2e6a70673111303058','Databricks',1641540030651,2,'databricks',NULL,NULL)
COMMIT;
BEGIN EXCLUSIVE;
SELECT _id, name, query, time, score  FROM search_queries WHERE type='2' OR type='12'
UPDATE search_queries SET score=1.94172375073327 WHERE _id='2'
UPDATE search_queries SET score=1.0 WHERE _id='10'
UPDATE search_queries SET score=0.999274223921473 WHERE _id='7'
UPDATE search_queries SET score=0.999851594082225 WHERE _id='9'
UPDATE search_queries SET score=0.997616141213516 WHERE _id='5'
COMMIT;
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479262008059047950'
SELECT _id, user_id, username, name, image_url, user_flags, user_label_data, is_profile_translatable, friendship, friendship_time, are_dms_muted, is_active_creator, profile_image_colors, has_nft_avatar, header_url, description, link_color, web_url, url_entities, bg_color, extended_profile_fields, location, structured_location, followers, fast_followers, friends, statuses, favorites, media_count, profile_created, updated, pinned_tweet_id, advertiser_type, hash, translator_type, profile_interstitial_type, profile_banner_colors, withheld_info, tip_jar_settings, smart_blocking_expiration, professional  FROM users WHERE user_id='1318236788541038594'
DELETE FROM timeline WHERE (type=26) AND (owner_id=1479345335860621312) AND (timeline_tag='VGltZWxpbmU6DABFAAA=')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('10044199219')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478975871000227843'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479100215382663170'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(2867,2866)
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1352681651516567553')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('1352681651516567553')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479080354145312770'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479052569917857792'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479093813779992581'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479210236619730950'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479090942208475136'
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('847528391163092993')
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('930484568305541120')
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1475885903251922944'
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN(2920)
SELECT _id, topic_id, topic_id_hash, name, is_following, description, is_not_interested, icon_url  FROM interest_topic WHERE topic_id IN('930484568305541120')
UPDATE timeline SET is_linger_impressed=1 WHERE _id IN()
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1469331164536217603'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478829153994608647'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479136625351401481'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1471959874049232899'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479016271945641985'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1479137523226062848'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478813301752700934'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478774817520242694'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478491933752311815'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='1478369879833075715'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='593878114465402880'
SELECT _id, status_id, author_id, content, created, in_r_user_id, in_r_status_id, in_r_screen_name, favorited, retweeted, favorite_count, retweet_count, quote_count, view_count, flags, latitude, longitude, place_data, card, lang, supplemental_language, quoted_tweet_id, reply_count, conversation_id, r_ent_content, self_thread_id, withheld_info, unified_card, is_reported, composer_source, tweet_source, quoted_status_permalink, limited_actions, conversation_control, auto_translation, has_birdwatch_notes, voice_info, birdwatch_pivot, super_follows_conversation_user_screen_name, super_follows_quoted_user_screen_name, reaction_metadata, exclusive_tweet_creator_screen_name, community_id, community, quick_promote_eligibility  FROM statuses WHERE status_id='451464503780065280'
